name: CI

on:
  workflow_dispatch:

jobs:
  Build_x64:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Sandboxie x86 (DLLs & svc)
        run: msbuild /t:build Sandboxie\SandboxDll.sln /p:Configuration="SbieRelease" /p:Platform=Win32

      - name: Build Sandboxie x64 (Drv)
        run: msbuild /t:build Sandboxie\core\drv\SboxDrv.vcxproj /p:Configuration="SbieRelease" /p:Platform=x64

      - uses: actions/upload-artifact@v4
        with:
          name: drv
          path: |
            Sandboxie/core/drv/Bin/*
